#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     sp_gyro,        sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     m_left,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     m_right,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    sp_grabber_l,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    sp_grabber_r,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// WARNING: Do not copy/paste autonomous hardware configuration!

#include "../lib/lib.h"
#include "common.c"

config_opt c_ramp;
config_opt c_delay;

void init_config() {
    c_ramp.name = "Ramp";
    c_ramp.levels[0] = 1;
    c_ramp.levels[1] = 0;
    c_ramp.levels[2] = CONFIG_END;

    c_delay.name = "Delay";
    c_delay.levels[0] = 0;
    c_delay.levels[1] = 5;
    c_delay.levels[2] = 10;
    c_delay.levels[3] = 15;
    c_delay.levels[4] = CONFIG_END;

    config_opt_list list;
    list.opts[0] = &c_ramp;
    list.opts[1] = &c_delay;
    list.length = 2;
    config_menu(list);
    writeDebugStreamLine("[init_config] Configuration OK");
}

void lift_up() {
    motor[lift] = 100;
    sleep(9000);
    motor[lift] = 0;
}

task lift_down() {
    motor[lift] = -100;
    sleep(8000);
    motor[lift] = 0;
}

void start_ground() {
}

void start_ramp() {
    writeDebugStreamLine("[autonomous] Starting from ramp...");
    drive_straight(30, 4000);
    sleep(500);

    // Operate lift and drop ball in goal.
    lift_up();
    servo_open(&servo_gate);
    sleep(1000);
    servo_close(&servo_gate);
    startTask(lift_down);

    // Grab goal and move to parking zone.
    grabber_down();
    sleep(1000);
    drive_straight(-30, 2000);
    sleep(500);
    gyro_turn_abs(-120);
    grabber_up();
    sleep(500);
    drive_straight(30, 5000);
}

task main() {
    init_config();
    waitForStart();
    init();
    gyro_init(sp_gyro, false);

    if (c_delay.value != 0) {
        writeDebugStreamLine("[autonomous] Waiting for %d seconds...", c_delay.value);
        sleep(c_delay.value * 1000);
    }

    if (c_ramp.value) {
        start_ramp();
    } else {
        start_ground();
    }

    writeDebugStreamLine("[autonomous] Finished!");
}
