#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     m_right,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     m_left,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    sp_grabber_r,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    sp_grabber_l,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../lib/drive.c"

void grabber_up() {
	servo[sp_grabber_l] = 245; //grabber up
  servo[sp_grabber_r] = 25;
}

void autonomous_init() {
	servo[gate] = 190;	//servo init
	grabber_up();
  drive_init(m_left, m_right);	//drivetrain initialize
}

void grabber_down() {
	servo[sp_grabber_l] = 89;  //grabber down
  servo[sp_grabber_r] = 177;
}

void lift_up() {
	motor[lift] = 100;
	wait1Msec(3000);
	motor[lift] = 0;
}

void lift_down() {
	motor[lift] = -20;
	wait1Msec(3000);
	motor[lift] = 0;
}


task main() {
    autonomous_init();
		waitForStart();
    bool on_ramp = true;  // whether robot is moving from ramp (vs. floor)
    if(on_ramp){
        drive_straight(-30, 3000);  // move backwards @30% power for 3s

        grabber_down();
        lift_up();
        servo[gate] = 80; //open gate
        wait1Msec(1000);	//wait for ball to roll into goal
        servo[gate] = 190;	//close gate
        lift_down();
				drive_straight(-30, 3000);  // move backwards @30% power for 3s

    }
    else {
        drive_straight(-30, 3000);  // move backwards @30% power for 3s

        grabber_down();
        lift_up();
        servo[gate] = 80; //open gate
        wait1Msec(1000);	//wait for ball to roll into goal
        servo[gate] = 190;	//close gate
        lift_down();
				drive_straight(-30, 3000);  // move backwards @30% power for 3s
    }
}
