#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     m_right,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     m_left,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabber_r,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    grabber_l,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../lib/drive.c"

void init() {
    drive_init(m_left, m_right);
    servo[gate] = 80;
}

task main() {
    waitForStart();
    init();

    while (true) {
        drive_handle_joystick();

        // Sweeper
        if (joy1Btn(7)) {
            motor[sweeper] = 100;
        } else if (joy1Btn(5)) {
            motor[sweeper] = -100;
        } else {
            motor[sweeper] = 0;
        }

        // Lift
        if (joy2Btn(6)) {
            motor[lift] = 100;  //lift up
        } else if (joy2Btn(8)) {
            motor[lift] = -20;  //lift down
        } else {
            motor[lift] = 0;
        }

        //Grabber
        if (joy1Btn(6)) {
            servo[grabber_l] = 220; //up
            servo[grabber_r] = 35;
        } else if (joy1Btn(8)) {
            servo[grabber_l] = 80;  //down
            servo[grabber_r] = 175;
        }

        // Gate
        if (joy2Btn(5)) {
            servo[gate] = 200;
        } else if (joy2Btn(7)) {
            servo[gate] = 80;
        }
    }
}
