#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     m_right,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     m_left,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    grabber_r,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    grabber_l,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libdrive.c"

void init() {
    drive_init(m_left, m_right);
}

task main() {
    waitForStart();
    init();

    while (true) {
        drive_handle_joystick();

        // Sweeper
        if (joy1Btn(7)) {
            motor[sweeper] = 50;
        } else {
            motor[sweeper] = 0;
        }

        // Lift
        if (joy2Btn(6)) {
            motor[lift] = 100;
        } else if (joy2Btn(8)) {
            motor[lift] = -50;
        } else {
            motor[lift] = 0;
        }

        // Gate
        if (joy1Btn(5)) {
        }
    }
}
