#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  motorA,          NA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          NA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          NA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Lever,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     Collect,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    Right,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    Left,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libdrive.c"

void init() {
    set_drivetrain(Left, Right);
}

task main() {
    init();
}
