#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C2_1,     m_left,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     m_right,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     m_carriage,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    sgl_port,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    sgr_port,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../libdrive.c"
#include "../libgyro.c"
#include "../libservo.c"

servo_s grabber_l;
servo_s grabber_r;

/**
 * Move the grabber to the up position.
 * @todo Put actual values here.
 */
void grabber_up() {
    servo_open(&grabber_l);
    servo_open(&grabber_r);
}

/**
 * Move the grabber to the down position.
 * @todo Put actual values here.
 */
void grabber_down() {
    servo_close(&grabber_l);
    servo_close(&grabber_r);
}

void init() {
    drive_init(m_left, m_right);
    gyro_init(gyro, false);
    grabber_up();
    gyro_calibrate();

    servo_init(&grabber_l, sgl_port, 90, 120);
    servo_init(&grabber_r, sgr_port, 90, 120);
}

task main() {
    waitForStart();
    init();

    // Drive off ramp and towards rolling goals.
    drive_straight(50, 1000);
    drive_straight(60, 1500);

    // Grab rolling goal and dump ball.
    grabber_down();

    // Turn and drive towards parking zone.
    gyro_turn_abs(-135, 70);
    drive_straight(50, 1000);

    // Release rolling goal.
    grabber_up();
}
