#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     ir_left,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ir_right,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sp_gyro,        sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     m_right,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     m_left,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     m_arm,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     m_rack,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    sp_right,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    sp_left,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sp_claw,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "common.c"

// Currently, init_common() starts robot with grabbers open.
static bool servo_isopen = true;                //< Keep track of current grabber state

static void init() {
    _drive_power = 100;
}

task main() {
    writeDebugStreamLine("[teleop] Started!");
    waitForStart();
    init_common();
    init();

    bool debounce_6 = true; //< True if button 6 is ready to be pressed

    while (true) {
        drive_joystick_power();
        drive_joystick_axes();

        if (joy1Btn(6)) {
            if (debounce_6 == true) {
	            if (servo_isopen) {
	                grabber_down(false);
	            } else {
	                grabber_up(false);
	            }
	            servo_isopen = !servo_isopen;
                debounce_6 = false;
            }
        } else {
            debounce_6 = true;
        }

        // Rack (controller 2)
        motor[m_rack] = joystick.joy2_y1;

        // Ball arm (controller 2)
        motor[m_arm] = joystick.joy2_y2 * 0.25;

        // Ball-grabbing claw (controller 2)
        if (joy2Btn(8)) {
            servo[sp_claw] = 145;
        } else if (joy2Btn(6)) {
            servo[sp_claw] = 45;
        }

        // Limit loop to 10 updates per second.
        Sleep(1000 / 10);
    }
}
